name: Generate Pacman Contribution Graph

on:
  schedule:
    - cron: "0 0 * * *"  # Executa todo dia à meia-noite
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Generate SVG
        uses: Platane/snk@v3
        with:
          github_user_name: speedyxbr
          outputs: |
            ./output/pacman-contribution-graph.svg
            ./output/pacman-contribution-graph-dark.svg

      - name: Push generated SVG
        uses: EndBug/add-and-commit@v9
        with:
          author_name: GitHub Action
          author_email: action@github.com
          message: 'gerando gráfico de contribuição pacman 🟣'
